apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.host }}
spec:
  secretName: {{ .Values.host }}
  dnsNames:
    - {{ .Values.host }}
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
