apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.deployment.name}}
  labels:
    app: {{.Values.deployment.name}}
spec:
  replicas: {{.Values.deployment.replicas}}
  selector:
    matchLabels:
      app: {{.Values.deployment.name}}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: {{.Values.deployment.name}}
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - image: thomseddon/traefik-forward-auth:2
        name: {{.Values.deployment.name}}
        ports:
          - containerPort: {{.Values.service.port}}
            protocol: TCP
        env:
          - name: DEFAULT_PROVIDER
            value: generic-oauth
          - name: PROVIDERS_GENERIC_OAUTH_AUTH_URL
            value: {{.Values.deployment.env.authUrl}}
          - name: PROVIDERS_GENERIC_OAUTH_TOKEN_URL
            value: {{.Values.deployment.env.tokenUrl}}
          - name: PROVIDERS_GENERIC_OAUTH_USER_URL
            value: {{.Values.deployment.env.userUrl}}
          - name: PROVIDERS_GENERIC_OAUTH_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: {{.Values.secret.name}}
                key: client_id
          - name: PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: {{.Values.secret.name}}
                key: client_secret
          - name: SECRET
            valueFrom:
              secretKeyRef: 
                name: {{.Values.secret.name}}
                key: secret
          - name: PROVIDERS_GENERIC_OAUTH_SCOPE
            value: {{.Values.deployment.env.oauthScope}}
