apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: {{ .Values.host }}
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - kind: Rule
      match: Host(`{{ .Values.host }}`)
      services:
        - kind: Service
          name: padawan
          port: 80
      middlewares:
        - name: {{ .Values.middleware.name }}
  tls:
    secretName: {{ .Values.host }}
