apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: padawan
rules:
  - apiGroups: 
      - "*"
    resources:
      - statefulsets
      - serviceaccounts
      - roles
      - rolebindings
      - secrets
      - services
    verbs:
      - "*"
