apiVersion: v1
kind: Secret
metadata:
  name: mysql-credentials
type: Opaque
stringData:
  mysql-root-password: verystrongpassword
  mysql-password: verystrongpassword
  username: padawan
  dbname: padawan