apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Name }}
subjects:
- kind: ServiceAccount
  name: {{ .Name }}
roleRef:
  kind: Role
  name: {{ .Name }}
  apiGroup: rbac.authorization.k8s.io