apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Name }}
rules:
  - apiGroups: 
      - "*"
    resources:
      - pods
    verbs:
      - get
      - list
    resourceNames:
      - {{ .Name }}-0
  - apiGroups: 
      - "*"
    resources:
      - pods/exec
    verbs: 
      - create
    resourceNames:
      - {{ .Name }}-0
