apiVersion: apps/v1
kind: Deployment
metadata:
  name: padawan-back
  labels:
    app: padawan
    tier: backend
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: padawan
      tier: backend
  template:
    metadata:
      labels:
        app: padawan
        tier: backend
    spec:
      serviceAccountName: padawan
      containers:
        - name: padawan
          image: registry.viarezo.fr/flow/padawanback:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: ADMINS
              valueFrom:
                configMapKeyRef:
                  name: padawan-admins
                  key: admins
            - name: DB_HOST
              value: {{ .Release.Name }}-mysql
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: dbname
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: mysql-password
