apiVersion: v1
kind: Service
metadata:
  name: {{.Values.service.name}}
  labels:
    app: {{.Values.deployment.name}}
spec:
  type: {{.Values.service.type}}
  selector:
    app: {{.Values.deployment.name}}
  ports:
  - name: auth-http
    port: {{.Values.service.port}}
    targetPort: 4181